/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DaySelect: typeof import('./src/components/DocumentDate/DaySelect.vue')['default']
    MonthSelect: typeof import('./src/components/DocumentDate/MonthSelect.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    YearSelect: typeof import('./src/components/DocumentDate/YearSelect.vue')['default']
  }
}
