/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/StepperPage': RouteRecordInfo<'/StepperPage', '/StepperPage', Record<never, never>, Record<never, never>>,
    '/steps/DocumentDatePage': RouteRecordInfo<'/steps/DocumentDatePage', '/steps/DocumentDatePage', Record<never, never>, Record<never, never>>,
    '/steps/PaymentDatePage': RouteRecordInfo<'/steps/PaymentDatePage', '/steps/PaymentDatePage', Record<never, never>, Record<never, never>>,
    '/steps/SummaryPage': RouteRecordInfo<'/steps/SummaryPage', '/steps/SummaryPage', Record<never, never>, Record<never, never>>,
  }
}
